- hosts: all
  tasks:
    #- name: stop container
    #  shell:  docker container stop rockstar-container                    #name of container 
    #- name: remove container
     # shell: docker container rm rockstar-container
    #- name: remove docker image
   #   shell: docker image rm trainingskumar/docker-job2                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name webcontainer -p 9000:80 akhilesh48455/webproject     #(docker-job>> name of jenkins job)
